alias vi="nvim"
[[ "$(uname -s)" == "Linux" ]] && alias nrs="sudo nixos-rebuild switch --flake ~/.config/nix#neon"
alias gr="go run ."
alias cr="cargo run"
alias p="pnpm"
alias f="yazi"
alias xcode="xed"
alias cf="clang-format"
alias dc="docker compose"
alias ls="eza --no-filesize --long --color=always --icons=always --no-user"
alias lz="lazygit"
alias s="fastfetch"
